In [1]:
import numpy as np

In [2]:
data = [6, 7.5, 8, 0, 1]
array_1 = np.array(data)

print("Array: " + str(array_1))
array_1.dtype

Array: [6.  7.5 8.  0.  1. ]


dtype('float64')

In [3]:
data_2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
array_2 = np.array(data_2)

array_2
print("Array dimensions: " + str(array_2.ndim))
print("Array shape: " + str(array_2.shape))
print("Rows: " + str(array_2.shape[0]))
print("Columns: " + str(array_2.shape[1]))
print("Type: " + str(array_2.dtype))

Array dimensions: 2
Array shape: (2, 5)
Rows: 2
Columns: 5
Type: int32


In [4]:
zero_array = np.zeros(10)
print("Array of zeros: " + str(zero_array))

zero_matrix = np.zeros((2, 3))
print("Matrix of zeros: " + str(zero_matrix))
print("Rows: " + str(zero_matrix.shape[0]))
print("Columns: " + str(zero_matrix.shape[1]))

Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Matrix of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Rows: 2
Columns: 3


In [5]:
range_array = np.arange(15)
print("Array in a range: " + str(range_array))

Array in a range: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
int_array = np.array([1, 2, 3, 4, 5])
float_array = int_array.astype(np.float64)
string_array_of_numbers = np.array(['1', '2.5', '3', '5.6'])
print("String array of numbers: " + str(string_array_of_numbers))
string_to_number_array = string_array_of_numbers.astype(np.float64)
print("Numeric array from string: " + str(string_to_number_array))

String array of numbers: ['1' '2.5' '3' '5.6']
Numeric array from string: [1.  2.5 3.  5.6]


In [7]:
op_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum: " + str(op_array + op_array))
print("Diff: " + str(op_array - op_array))
print("Mult: " + str(op_array * op_array))
print("Div: " + str(op_array / op_array))

Sum: [[ 2  4  6]
 [ 8 10 12]]
Diff: [[0 0 0]
 [0 0 0]]
Mult: [[ 1  4  9]
 [16 25 36]]
Div: [[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
indexing_array = np.arange(10)
print("Array: " + str(indexing_array))
indexing_array[5]
indexing_array[5:8]
arr_slice = indexing_array[5:8]
arr_slice[1] = 1234
indexing_array

Array: [0 1 2 3 4 5 6 7 8 9]


array([   0,    1,    2,    3,    4,    5, 1234,    7,    8,    9])

In [9]:
array_2d = np.array([[1, 2, 3], [4 ,5 ,6], [7, 8, 9]])
array_2d[1]
array_2d[0, 2]
array_2d[1:, 1:]
array_2d[:, 0] = 0
array_2d

array([[0, 2, 3],
       [0, 5, 6],
       [0, 8, 9]])

In [10]:
names = np.array(["Antonio", "Mike", "Heisenberg", "Elliot", "Charles", "Carlos", "Lewis", "Max"])
boolean_array = (names == "Mike")
boolean_array
boolean_array_opposite = (names != "Mike")
boolean_array_opposite

array([ True, False,  True,  True,  True,  True,  True,  True])

In [11]:
random_data = np.random.randn(7, 4)
random_data
random_data[random_data > 0]

array([1.54581507, 1.59113842, 1.04529972, 0.41096417, 1.25875399,
       0.06595151, 0.68690363, 0.43132957, 0.80932311, 2.94205804,
       0.96202728, 1.51756004, 1.28297307, 0.06577895, 0.03374607,
       0.82601361, 0.21242896])

In [12]:
fancy_array = np.empty((8, 4))
for i in range(fancy_array.shape[0]):
    fancy_array[i] = i
    
fancy_array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [13]:
transpose_array = np.arange(15).reshape(3, 5)
transpose_array
transpose_array.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [14]:
array_for_functions = np.arange(10).reshape(2, 5)
array_for_functions
np.sqrt(array_for_functions)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [15]:
array_one = np.random.randn(10)
array_two = np.random.randn(10)
np.maximum(array_one, array_two)

array([0.67909873, 0.86811384, 1.26586334, 1.73980427, 0.27987485,
       2.33869015, 0.46013674, 1.44046933, 0.78183827, 1.17358249])

In [16]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2,  2],
       [-2, -2, -2,  2]])

In [22]:
arr = np.random.randn(5, 4)
arr.mean()
arr.mean(axis=1)
arr.mean(axis=0)

array([-0.13353412,  0.33769235,  0.16911039, -0.57209876])

In [23]:
arr = np.random.randn(100)
(arr > 0).sum()

47

In [25]:
bools = np.array([True, False, False, True, True])
bools.any()
bools.all()

False

In [27]:
arr = np.random.randn(8)
arr.sort()
arr

array([-0.96264179, -0.65496975, -0.31628753, -0.23806805,  0.06039596,
        0.13529791,  0.89831343,  2.27734817])

In [30]:
arr = np.random.randn(3, 8)
arr.sort(1)
arr

array([[-0.55490256, -0.43445468, -0.41334208, -0.01180592,  0.07401781,
         0.70926806,  0.80946918,  1.11949535],
       [-2.03972767, -0.99237611, -0.39824306, -0.28862562, -0.23544095,
        -0.2092554 ,  0.75841362,  0.8929185 ],
       [-0.60618819,  0.04243707,  0.11066474,  0.18015686,  0.27850505,
         0.62536078,  1.62385658,  1.8780634 ]])

In [33]:
names = np.array(["Lewis", "Max", "George", "Max", "Lewis"])
unique_names = np.unique(names)
unique_names

array(['George', 'Lewis', 'Max'], dtype='<U6')