In [1]:
import numpy as np

In [3]:
array_1 = np.array([1, 2, 3])
print(array_1)

[1 2 3]


In [10]:
array_2 = np.array([[1, 2], [3, 4]])
print(array_2)

[[1 2]
 [3 4]]
[2 4]


In [11]:
array_3 = np.array([1, 2, 3, 4, 5], ndmin=2)
print(array_3)

[[1 2 3 4 5]]


In [12]:
array_4 = np.array([1, 2, 3], dtype=complex)
print(array_4)

[1.+0.j 2.+0.j 3.+0.j]


In [14]:
array_5 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_5.shape)

(2, 3)


In [15]:
array_5.shape = (3, 2)
print(array_5)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
array_b5 = array_5.reshape(3, 2)
print(array_b5)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
array_6 = np.arange(24)
print(array_6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [20]:
zero_1_dim = np.zeros(5)
print(zero_1_dim)

[0. 0. 0. 0. 0.]


In [21]:
zero_2_dim = np.zeros((2, 5))
print(zero_2_dim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
