In [1]:
import numpy as np

In [11]:
data = [6, 7.5, 8, 0, 1]
array_1 = np.array(data)

print("Array: " + str(array_1))
array_1.dtype

Array: [6.  7.5 8.  0.  1. ]


dtype('float64')

In [13]:
data_2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
array_2 = np.array(data_2)

array_2
print("Array dimensions: " + str(array_2.ndim))
print("Array shape: " + str(array_2.shape))
print("Rows: " + str(array_2.shape[0]))
print("Columns: " + str(array_2.shape[1]))
print("Type: " + str(array_2.dtype))

Array dimensions: 2
Array shape: (2, 5)
Rows: 2
Columns: 5
Type: int32


In [18]:
zero_array = np.zeros(10)
print("Array of zeros: " + str(zero_array))

zero_matrix = np.zeros((2, 3))
print("Matrix of zeros: " + str(zero_matrix))
print("Rows: " + str(zero_matrix.shape[0]))
print("Columns: " + str(zero_matrix.shape[1]))

Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Matrix of zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Rows: 2
Columns: 3


In [19]:
range_array = np.arange(15)
print("Array in a range: " + str(range_array))

Array in a range: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
int_array = np.array([1, 2, 3, 4, 5])
float_array = int_array.astype(np.float64)
string_array_of_numbers = np.array(['1', '2.5', '3', '5.6'])
print("String array of numbers: " + str(string_array_of_numbers))
string_to_number_array = string_array_of_numbers.astype(np.float64)
print("Numeric array from string: " + str(string_to_number_array))

String array of numbers: ['1' '2.5' '3' '5.6']
Numeric array from string: [1.  2.5 3.  5.6]


In [22]:
op_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum: " + str(op_array + op_array))
print("Diff: " + str(op_array - op_array))
print("Mult: " + str(op_array * op_array))
print("Div: " + str(op_array / op_array))

Sum: [[ 2  4  6]
 [ 8 10 12]]
Diff: [[0 0 0]
 [0 0 0]]
Mult: [[ 1  4  9]
 [16 25 36]]
Div: [[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
indexing_array = np.arange(10)
print("Array: " + str(indexing_array))
indexing_array[5]
indexing_array[5:8]
arr_slice = indexing_array[5:8]
arr_slice[1] = 1234
indexing_array

Array: [0 1 2 3 4 5 6 7 8 9]


array([   0,    1,    2,    3,    4,    5, 1234,    7,    8,    9])

In [44]:
array_2d = np.array([[1, 2, 3], [4 ,5 ,6], [7, 8, 9]])
array_2d[1]
array_2d[0, 2]
array_2d[1:, 1:]
array_2d[:, 0] = 0
array_2d

array([[0, 2, 3],
       [0, 5, 6],
       [0, 8, 9]])

In [47]:
names = np.array(["Antonio", "Mike", "Heisenberg", "Elliot", "Charles", "Carlos", "Lewis", "Max"])
boolean_array = (names == "Mike")
boolean_array
boolean_array_opposite = (names != "Mike")
boolean_array_opposite

array([ True, False,  True,  True,  True,  True,  True,  True])

In [53]:
random_data = np.random.randn(7, 4)
random_data
random_data[random_data > 0]

array([0.24170359, 0.13795452, 0.55834472, 0.31758513, 0.07115818,
       0.15641107, 0.31554921, 0.88855433, 1.29829164, 1.0672205 ,
       0.6135144 , 0.16775058, 0.76739817, 1.91145099])

In [54]:
fancy_array = np.empty((8, 4))
for i in range(fancy_array.shape[0]):
    fancy_array[i] = i
    
fancy_array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
transpose_array = np.arange(15).reshape(3, 5)
transpose_array
transpose_array.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
array_for_functions = np.arange(10).reshape(2, 5)
array_for_functions
np.sqrt(array_for_functions)

TypeError: maximum() takes from 2 to 3 positional arguments but 1 were given

In [60]:
array_one = np.random.randn(10)
array_two = np.random.randn(10)
np.maximum(array_one, array_two)

array([ 0.46928558,  0.0358087 , -0.59292108,  0.98413939,  1.41901455,
       -0.47650927, -0.20663662,  1.77228068,  0.71125348,  0.59087306])